# Generated by Django 3.1.4 on 2021-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='', max_length=500, null=True),
        ),
    ]
