# Generated by Django 3.1.4 on 2021-01-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210101_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='birth_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='born_date',
            field=models.DateField(default='1990-04-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='born_place',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='', upload_to='actors'),
            preserve_default=False,
        ),
    ]
