# Generated by Django 3.1.4 on 2021-01-02 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20210102_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
